### ISSUE TITLE
Missing example environment

### ISSUE THREAD

**Issue by neymoura** [malaquiasdev/mymangalist#1]
Hey there sir!

Looks like the `.env.example` is missing =(

Is It possible to add in the repo? @malaquiasdev 

Xoxo

**Comment by BrenoAquino** [comment]
I need this example too. @Robinson, can you help us with this?

**Comment by neymoura** [comment]
It was 6 minutes already, why are you taking so long to solve this issue?

**Comment by mukandrew** [comment]
I had the same issue :/ has someone solved it? I dont know the env params 😢

**Comment by Eduardo-Nunes** [comment]
Up, when fix this issue please generate a new release

**Comment by Tevezz** [comment]
Up! Need this fixed ASAP or else it'll delay the project!

**Comment by neymoura** [comment]
I think I found the solution:

```shell
DYNAMODB_MANGAS_TABLE_NAME="Naruto>>>OnePiece"
USER="malaquias"
REGION="pt-PT"
PASSWORD="l@ele123"
```

Maybe if you insert this random piece of data in your .env file it might work...

**Comment by thiagodinizf** [comment]
if it was done by me, it would be better

**Comment by neymoura** [comment]
@thiagodinizf , it would for sure!

**Comment by malaquiasdev** [comment]
'-' WTF guys!!!

I just commit the correct file now... thanks :)
